### ISSUE TITLE
React plugin

### ISSUE THREAD

**Issue by jasonkuhrt** [littlebits/code-standards-js#6]
React is a key technology at littleBits so we should start linting it with [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react).

**Comment by jasonkuhrt** [comment]
Lint rules that we should apply initially:

``` yaml
react/display-name:
  - 1
  - acceptTranspilerName: true
react/jsx-uses-react:
  - 1
react/wrap-multilines:
  - 1
react/sort-comp: # See default settings at blob/master/docs/rules/sort-comp.md
  - 1
react/react-in-jsx-scope:
  - 1
react/prop-types:
  - 1
react/no-direct-mutation-state:
  - 2
react/no-did-update-set-state:
  - 1
  - allow-in-func
react/no-deprecated:
  - 1
react/jsx-uses-vars:
  - 2
```

Some rules we may want to consider in the future:
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md
